### ISSUE TITLE
Can this framework be used for tabular data?

### ISSUE THREAD

**Issue by soheilre** [ThunderStruct/HiveNAS#1]
Hello
This tool is very good
Can this framework be used for tabular data?
If possible, explain more
Thanks

**Comment by ThunderStruct** [comment]
Hi!

This framework can be used to find neural architectures for supervised learning classification problems, regardless of the data-type. The tool was built specifically for _image datasets_, but can be applied to tabular data as well. All you need to do is define the dataset loader in [NASEval.\_\_init\_\_()](https://hivenas.readthedocs.io/en/latest/api/core.nas.evaluation_strategy.html#core.nas.evaluation_strategy.NASEval).

I'm not sure what your data consists of, but make sure you actually need Deep Learning to solve it as **HiveNAS** currently only supports the generation of CNNs. If your data does not require intermediate representations, I would suggest experimenting with other ML models.

Good luck!

**Comment by ThunderStruct** [comment]
Added to the docs in bae9ec706e08f7940516cafc535f67ccb1754775.
